### ISSUE TITLE
Unable to find credentials

### ISSUE THREAD

**Issue by KeparYTbcc** [Ge0rg3/requests-ip-rotator#31]
```
Starting API gateways in 10 regions.
Traceback (most recent call last):
  File "C:\Users\my-pc2\Downloads\Kepar stuff\SB\nekodownload\nekodownload copy.py", line 152, in <module>
    with ApiGateway("https://nekobot.xyz") as g:
  File "C:\Users\my-pc2\AppData\Local\Programs\Python\Python310\lib\site-packages\requests_ip_rotator\ip_rotator.py", line 47, in __enter__
    self.start()
  File "C:\Users\my-pc2\AppData\Local\Programs\Python\Python310\lib\site-packages\requests_ip_rotator\ip_rotator.py", line 250, in start
    result = future.result()
  File "C:\Users\my-pc2\AppData\Local\Programs\Python\Python310\lib\concurrent\futures\_base.py", line 438, in result
    return self.__get_result()
  File "C:\Users\my-pc2\AppData\Local\Programs\Python\Python310\lib\concurrent\futures\_base.py", line 390, in __get_result
    raise self._exception
  File "C:\Users\my-pc2\AppData\Local\Programs\Python\Python310\lib\concurrent\futures\thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "C:\Users\my-pc2\AppData\Local\Programs\Python\Python310\lib\site-packages\requests_ip_rotator\ip_rotator.py", line 86, in init_gateway
    current_apis = awsclient.get_rest_apis()["items"]
  File "C:\Users\my-pc2\AppData\Local\Programs\Python\Python310\lib\site-packages\botocore\client.py", line 395, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "C:\Users\my-pc2\AppData\Local\Programs\Python\Python310\lib\site-packages\botocore\client.py", line 711, in _make_api_call
    http, parsed_response = self._make_request(
  File "C:\Users\my-pc2\AppData\Local\Programs\Python\Python310\lib\site-packages\botocore\client.py", line 731, in _make_request
    return self._endpoint.make_request(operation_model, request_dict)
  File "C:\Users\my-pc2\AppData\Local\Programs\Python\Python310\lib\site-packages\botocore\endpoint.py", line 107, in make_request
    return self._send_request(request_dict, operation_model)
  File "C:\Users\my-pc2\AppData\Local\Programs\Python\Python310\lib\site-packages\botocore\endpoint.py", line 180, in _send_request
    request = self.create_request(request_dict, operation_model)
  File "C:\Users\my-pc2\AppData\Local\Programs\Python\Python310\lib\site-packages\botocore\endpoint.py", line 120, in create_request
    self._event_emitter.emit(event_name, request=request,
  File "C:\Users\my-pc2\AppData\Local\Programs\Python\Python310\lib\site-packages\botocore\hooks.py", line 357, in emit
    return self._emitter.emit(aliased_event_name, **kwargs)
  File "C:\Users\my-pc2\AppData\Local\Programs\Python\Python310\lib\site-packages\botocore\hooks.py", line 228, in emit
    return self._emit(event_name, kwargs)
  File "C:\Users\my-pc2\AppData\Local\Programs\Python\Python310\lib\site-packages\botocore\hooks.py", line 211, in _emit
    response = handler(**kwargs)
  File "C:\Users\my-pc2\AppData\Local\Programs\Python\Python310\lib\site-packages\botocore\signers.py", line 93, in handler
    return self.sign(operation_name, request)
  File "C:\Users\my-pc2\AppData\Local\Programs\Python\Python310\lib\site-packages\botocore\signers.py", line 165, in sign
    auth.add_auth(request)
  File "C:\Users\my-pc2\AppData\Local\Programs\Python\Python310\lib\site-packages\botocore\auth.py", line 388, in add_auth
    raise NoCredentialsError()
botocore.exceptions.NoCredentialsError: Unable to locate credentials

C:\Users\my-pc2\Downloads\Kepar stuff\SB\nekodownload>
```

**Comment by KeparYTbcc** [comment]
```
import requests
import wget
import os
import os.path
from time import sleep
from requests_ip_rotator import ApiGateway

os.system('cls')

current = os.getcwd()

def bar_custom(current, total, width=0):
    pass

proxies = {
    "sock4" : "sock4://208.102.51.6:58208/",
    "sock4" : "sock4://72.206.181.105:64935/",
    "sock4" : "sock4://72.221.196.145:4145/",
    "sock4" : "sock4://222.212.85.16:7000/",
    "sock4" : "sock4://195.177.217.131:15004/",
    "sock4" : "sock4://72.221.172.203:4145/",
    "sock4" : "sock4://72.49.49.11:31034/",
    "sock4" : "sock4://192.241.178.187:20807/",
    "sock4" : "sock4://61.185.22.175:1080/",
    "sock4" : "sock4://51.222.12.245:10084/",
    "sock4" : "sock4://138.197.197.200:9050/",
    "sock4" : "sock4://198.8.94.170:4145/",
    "sock4" : "sock4://174.77.111.198:49547/",
    "sock4" : "sock4://72.195.34.59:4145/",
    "sock4" : "sock4://45.67.229.104:30001/",
    "sock4" : "sock4://174.77.111.196:4145/",
    "sock4" : "sock4://70.185.68.133:4145/",
    "sock4" : "sock4://192.111.129.145:16894/",
    "sock4" : "sock4://49.51.69.212:21127/",
    "sock4" : "sock4://128.199.245.23:24527/",
    "sock4" : "sock4://206.189.237.58:38749/",
    "sock4" : "sock4://70.166.167.55:57745/",
    "sock4" : "sock4://173.212.248.58:1976/",
    "sock4" : "sock4://184.179.216.130:4145/",
    "sock4" : "sock4://192.111.135.18:18301/",
    "sock4" : "sock4://72.206.181.97:64943/",
    "sock4" : "sock4://184.178.172.13:15311/",
    "sock4" : "sock4://198.199.64.196:61877/",
    "sock4" : "sock4://67.205.191.23:18474/",
    "sock4" : "sock4://167.99.239.113:36118/",
    "sock4" : "sock4://72.223.168.67:4145/",
    "sock4" : "sock4://138.197.193.107:9050/",
    "sock4" : "sock4://198.12.121.71:38007/",
    "sock4" : "sock4://222.129.39.78:1081/",
    "sock4" : "sock4://198.199.64.196:46726/",
    "sock4" : "sock4://129.146.216.187:20000/",
    "sock4" : "sock4://49.51.189.171:21127/",
    "sock4" : "sock4://98.162.25.29:31679/",
    "sock4" : "sock4://167.71.170.135:54009/",
    "sock4" : "sock4://8.44.216.242:13333/",
    "sock4" : "sock4://193.70.46.201:56947/",
    "sock4" : "sock4://184.178.172.25:15291/",
    "sock4" : "sock4://192.111.139.162:4145/",
    "sock4" : "sock4://192.241.252.114:26613/",
    "sock4" : "sock4://72.223.168.73:57494/",
    "sock4" : "sock4://72.195.34.42:4145/",
    "sock4" : "sock4://118.212.58.197:8001/",
    "sock4" : "sock4://192.111.130.5:17002/",
    "sock4" : "sock4://192.252.209.155:14455/",
    "sock4" : "sock4://139.196.229.151:49580/",
    "sock4" : "sock4://112.163.21.154:23386/",
    "sock4" : "sock4://49.51.74.61:21127/",
    "sock4" : "sock4://173.212.248.58:17707/",
    "sock4" : "sock4://107.170.50.49:24722/",
    "sock4" : "sock4://91.205.72.103:15078/",
    "sock4" : "sock4://132.148.159.163:28556/",
    "sock4" : "sock4://165.232.134.201:9150/",
    "sock4" : "sock4://91.205.72.103:13643/",
    "sock4" : "sock4://50.62.30.5:20969/",
    "sock4" : "sock4://46.101.5.73:48528/",
    "sock4" : "sock4://46.101.36.144:11475/",
    "sock4" : "sock4://72.221.196.157:35904/",
    "sock4" : "sock4://163.172.111.6:51119/",
    "sock4" : "sock4://24.249.199.4:4145/",
    "sock4" : "sock4://117.89.131.218:1080/",
    "sock4" : "sock4://192.111.137.37:18762/",
    "sock4" : "sock4://167.114.36.197:36020/",
    "sock4" : "sock4://49.51.186.129:21127/",
    "sock4" : "sock4://72.195.114.184:4145/",
    "sock4" : "sock4://27.254.208.59:1080/",
    "sock4" : "sock4://72.210.252.137:4145/",
    "sock4" : "sock4://184.179.216.133:24630/",
    "sock4" : "sock4://184.178.172.14:4145/",
    "sock4" : "sock4://171.224.229.183:5004/",
    "sock4" : "sock4://192.252.220.92:17328/",
    "sock4" : "sock4://67.201.33.10:25283/",
    "sock4" : "sock4://167.114.165.210:38759/",
    "sock4" : "sock4://174.64.199.82:4145/",
    "sock4" : "sock4://192.252.208.67:14287/",
    "sock4" : "sock4://125.141.139.112:5566/",
    "sock4" : "sock4://92.222.206.151:39101/",
    "sock4" : "sock4://98.178.72.21:10919/",
    "sock4" : "sock4://159.65.106.51:9050/",
    "sock4" : "sock4://104.131.8.62:26147/",
    "sock4" : "sock4://121.43.62.156:1080/",
    "sock4" : "sock4://142.93.137.235:50558/",
    "sock4" : "sock4://103.240.160.21:6667/",
    "sock4" : "sock4://184.178.172.18:15280/",
    "sock4" : "sock4://68.183.190.137:53977/",
    "sock4" : "sock4://72.221.232.155:4145/",
    "sock4" : "sock4://98.162.25.4:31654/",
    "sock4" : "sock4://68.183.111.220:45241/",
    "sock4" : "sock4://72.206.181.123:4145/",
    "sock4" : "sock4://72.221.164.34:60671/",
    "sock4" : "sock4://176.103.50.24:35544/",
    "sock4" : "sock4://51.222.13.193:10084/",
    "sock4" : "sock4://24.103.162.189:31337/",
    "sock4" : "sock4://98.170.57.231:4145/",
    "sock4" : "sock4://24.249.199.12:4145/",
    "sock4" : "sock4://198.8.94.174:39078/",
    "sock4" : "sock4://192.241.167.22:23983/",
    "sock4" : "sock4://128.199.138.28:64973/",
    "sock4" : "sock4://138.197.208.39:9050/",
    "sock4" : "sock4://117.30.39.128:1080/",
    "sock4" : "sock4://192.111.137.35:4145/",
    "sock4" : "sock4://72.195.34.35:27360/",
    "sock4" : "sock4://72.217.216.239:4145/",
    "sock4" : "sock4://78.47.230.141:17027/",
    "sock4" : "sock4://118.212.56.76:8001/",
    "sock4" : "sock4://184.178.172.28:15294/",
    "sock4" : "sock4://212.38.189.118:36491/",
    "sock4" : "sock4://92.222.206.151:2020/",
    "sock4" : "sock4://174.77.111.197:4145/",
    "sock4" : "sock4://69.61.200.104:36181/",
    "sock4" : "sock4://118.212.58.197:8003/",
    "sock4" : "sock4://159.203.33.4:32139/",
    "sock4" : "sock4://194.87.102.102:1111/",
    "sock4" : "sock4://85.25.198.22:5577/",
    "sock4" : "sock4://165.227.104.122:45119/",
    "sock4" : "sock4://165.227.104.122:34709/",
    "sock4" : "sock4://72.210.252.134:46164/",
    "sock4" : "sock4://36.137.57.38:82/",
    "sock4" : "sock4://72.195.34.41:4145/",
    "sock4" : "sock4://36.133.38.6:83/",
    "sock4" : "sock4://184.181.217.210:4145/",
    "sock4" : "sock4://192.111.139.165:4145/",
    "sock4" : "sock4://68.71.249.153:48606/",
    "sock4" : "sock4://171.224.229.183:5006/",
    "sock4" : "sock4://72.223.168.86:57481/",
    "sock4" : "sock4://72.206.181.103:4145/",
    "sock4" : "sock4://111.193.126.175:1080/",
    "sock4" : "sock4://174.75.211.222:4145/",
    "sock4" : "sock4://142.4.18.23:33425/",
    "sock4" : "sock4://192.111.135.21:4145/",
    "sock4" : "sock4://111.172.65.190:1081/",
}
with ApiGateway("https://nekobot.xyz") as g:
    while True:
        session = requests.Session()
        session.mount("https://nekobot.xyz", g)
        with session.get("https://nekobot.xyz/api/image?type=hthigh&image=") as r:
            res = r.json()
            image = res['message']
        if os.path.isfile(current + "\\images\\" + image[30:999990]) == True:
            pass
        else:
            try:
                a = wget.download(image, current + "\\images\\", bar=bar_custom)
                print('Downloaded: ' + current + "\\" + image[30:999990])
            except:
                print('Error retrying in a min')
                sleep(60)

```

**Comment by Ge0rg3** [comment]
Hi, closing this issue as unresponsive. Please let me know if you need any further help.
