### ISSUE TITLE
Parsing with a pool of 100 workers causes TooManyRequestsException

### ISSUE THREAD

**Issue by vincenthawke** [Ge0rg3/requests-ip-rotator#4]
I don’t know why, because I am not hitting any limits documented here: https://docs.aws.amazon.com/apigateway/latest/developerguide/limits.html#api-gateway-limits
According to this page, they allow for 10k requests per second.

```
multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python39\lib\multiprocessing\pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python39\lib\multiprocessing\pool.py", line 48, in mapstar
    return list(map(*args))
  File "C:\Users\Admin\PycharmProjects\WhatIsMyIP\aws_proxytester.py", line 31, in proxyLoop
    getIP()
  File "C:\Users\Admin\PycharmProjects\WhatIsMyIP\aws_proxytester.py", line 14, in getIP
    gateway_1.start()
  File "C:\Users\Admin\PycharmProjects\WhatIsMyIP\venv\lib\site-packages\requests_ip_rotator\ip_rotator.py", line 243, in start
    result = future.result()
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python39\lib\concurrent\futures\_base.py", line 438, in result
    return self.__get_result()
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python39\lib\concurrent\futures\_base.py", line 390, in __get_result
    raise self._exception
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python39\lib\concurrent\futures\thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "C:\Users\Admin\PycharmProjects\WhatIsMyIP\venv\lib\site-packages\requests_ip_rotator\ip_rotator.py", line 74, in init_gateway
    raise e
  File "C:\Users\Admin\PycharmProjects\WhatIsMyIP\venv\lib\site-packages\requests_ip_rotator\ip_rotator.py", line 66, in init_gateway
    current_apis = awsclient.get_rest_apis()["items"]
  File "C:\Users\Admin\PycharmProjects\WhatIsMyIP\venv\lib\site-packages\botocore\client.py", line 386, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "C:\Users\Admin\PycharmProjects\WhatIsMyIP\venv\lib\site-packages\botocore\client.py", line 705, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.errorfactory.TooManyRequestsException: An error occurred (TooManyRequestsException) when calling the GetRestApis operation (reached max retries: 4): Too Many Requests
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\Admin\PycharmProjects\WhatIsMyIP\aws_proxytester.py", line 40, in <module>
    p.map(proxyLoop, list1)
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python39\lib\multiprocessing\pool.py", line 364, in map
    return self._map_async(func, iterable, mapstar, chunksize).get()
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python39\lib\multiprocessing\pool.py", line 771, in get
    raise self._value
botocore.exceptions.ClientError: An error occurred (TooManyRequestsException) when calling the GetRestApis operation (reached max retries: 4): Too Many Requests

```
My script to reproduce results:
```
# requires pip install urllib3==1.25.8 for proxies to work
import requests
from requests_ip_rotator import ApiGateway, EXTRA_REGIONS, ALL_REGIONS
from bs4 import BeautifulSoup
from timeit import default_timer as timer
from multiprocessing import Pool

domain = "https://www.showmyip.com/"
site = "https://www.showmyip.com/"
gateway_1 = ApiGateway(domain, regions=["eu-west-1"])
def getIP():
    headers = {'Connection': 'close', 'Request-Timeout': '1'}

    gateway_1.start()
    session_1 = requests.Session()
    session_1.mount(domain, gateway_1)
    response = session_1.get(site, headers=headers)
    print(f"Status code: {response.status_code}\n")
    print(f"Request headers: {response.request.headers['Host']}\n")
    # print(f"Response headers: {response.headers}\n")

    try:
        soup = BeautifulSoup(response.text, 'html.parser')
        myip = soup.find('h2').text
        print(f"IP: {myip}")
    except:
        print("error parsing html")

def proxyLoop(loop_count):
    try:
        getIP()
    except OSError as error:
        print(f"Error message: {error}")


if __name__ == '__main__':
    start = timer()
    list1 = list(range(1, 1000))
    p = Pool(100)
    p.map(proxyLoop, list1)
    end = timer()
    print(f"Time: {end - start}")
    gateway_1.shutdown()

```

**Comment by vincenthawke** [comment]
That was fast:) What I did was move ```
gateway_1.start()
session_1 = requests.Session()
```
out of the function so it only gets called once at start and I reduced the number of pool workers to 60, becuase I was getting an exception that is nto part of this issue. It worked and completed all 1000 requests in 12 seconds. AWS and this module are sick!! 😄

**Comment by Ge0rg3** [comment]
Glad to hear it!

Please also keep in mind that this method will be slightly slower than a fixed endpoints array, as the gateway.start() auto-discovery request will be sent on each process launch (due to the nature of multiprocesses).
